#include <stdio.h>
#include <gmp.h>
/* Problem 2 from Project Euler
Solution by Paul Barton

Here is the text of the problem:
Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.

There are several ways to simplify the approach to this problem and reduce
the number of calculations. For now, I will leave them alone and only present
a basic fibonacci algorithm.*/

int main () {
    mpz_t max;
    mpz_t a;
    mpz_t b;
    mpz_t c;
    mpz_init(c);
    mpz_init_set_ui(a, 1);
    mpz_init_set_ui(b, 2);
    mpz_init_set_ui(max, 4000000);
    
    mpz_t count;
    mpz_t mod;
    mpz_init(mod);
    mpz_init_set_ui(count, 2);
    while (mpz_cmp(b, max) < 0) { //mpz_cmp returns a negative value if b < max
        mpz_mod_ui(mod, b, 2);
        if (mpz_cmp_ui(mod, 0) == 1) {
            mpz_add(count, count, b);
        }
        gmp_printf("%Zd\n", a);
        mpz_add(c, a, b);
        mpz_set(a, b);
        mpz_set(b, c);
    }
    gmp_printf("%Zd\n%Zd\n", a, b);
    gmp_printf("The count is %Zd\n", count);
}